CREATE TABLE `users`(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(15) NOT NULL,
    picture VARCHAR(255),
    status VARCHAR(125),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);

ALTER TABLE users ADD specialization VARCHAR(255);
ALTER TABLE users ADD deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE users RENAME COLUMN status TO state;
ALTER TABLE users RENAME COLUMN picture TO url_picture;
