// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	patient "github.com/dr-ariawan-s-project/api-drariawan/features/patient"
	mock "github.com/stretchr/testify/mock"
)

// PatientData is an autogenerated mock type for the PatientDataInterface type
type PatientData struct {
	mock.Mock
}

// CheckByEmailAndPhone provides a mock function with given fields: email, phone
func (_m *PatientData) CheckByEmailAndPhone(email string, phone string) (*patient.Core, error) {
	ret := _m.Called(email, phone)

	var r0 *patient.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*patient.Core, error)); ok {
		return rf(email, phone)
	}
	if rf, ok := ret.Get(0).(func(string, string) *patient.Core); ok {
		r0 = rf(email, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAllPatient provides a mock function with given fields:
func (_m *PatientData) CountAllPatient() (int, error) {
	ret := _m.Called()

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByFilter provides a mock function with given fields: search
func (_m *PatientData) CountByFilter(search string) (int64, error) {
	ret := _m.Called(search)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(search)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(search)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountPartner provides a mock function with given fields: partnerId
func (_m *PatientData) CountPartner(partnerId string) (int, error) {
	ret := _m.Called(partnerId)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(partnerId)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(partnerId)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(partnerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *PatientData) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: data
func (_m *PatientData) Insert(data patient.Core) (*patient.Core, error) {
	ret := _m.Called(data)

	var r0 *patient.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(patient.Core) (*patient.Core, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(patient.Core) *patient.Core); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(patient.Core) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Select provides a mock function with given fields: search, offset, limit
func (_m *PatientData) Select(search string, offset int, limit int) ([]patient.Core, error) {
	ret := _m.Called(search, offset, limit)

	var r0 []patient.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]patient.Core, error)); ok {
		return rf(search, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []patient.Core); ok {
		r0 = rf(search, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]patient.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(search, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectAllNIK provides a mock function with given fields:
func (_m *PatientData) SelectAllNIK() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectByEmailOrPhone provides a mock function with given fields: str
func (_m *PatientData) SelectByEmailOrPhone(str string) (*patient.Core, error) {
	ret := _m.Called(str)

	var r0 *patient.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*patient.Core, error)); ok {
		return rf(str)
	}
	if rf, ok := ret.Get(0).(func(string) *patient.Core); ok {
		r0 = rf(str)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(str)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectById provides a mock function with given fields: id
func (_m *PatientData) SelectById(id string) (*patient.Core, error) {
	ret := _m.Called(id)

	var r0 *patient.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*patient.Core, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *patient.Core); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, data
func (_m *PatientData) Update(id string, data patient.Core) (*patient.Core, error) {
	ret := _m.Called(id, data)

	var r0 *patient.Core
	var r1 error
	if rf, ok := ret.Get(0).(func(string, patient.Core) (*patient.Core, error)); ok {
		return rf(id, data)
	}
	if rf, ok := ret.Get(0).(func(string, patient.Core) *patient.Core); ok {
		r0 = rf(id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*patient.Core)
		}
	}

	if rf, ok := ret.Get(1).(func(string, patient.Core) error); ok {
		r1 = rf(id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPatientData interface {
	mock.TestingT
	Cleanup(func())
}

// NewPatientData creates a new instance of PatientData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPatientData(t mockConstructorTestingTNewPatientData) *PatientData {
	mock := &PatientData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
