// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	questionaire "github.com/dr-ariawan-s-project/api-drariawan/features/questionaire"
	mock "github.com/stretchr/testify/mock"
)

// QuestionaireData is an autogenerated mock type for the QuestionaireDataInterface type
type QuestionaireData struct {
	mock.Mock
}

// CheckCountAttemptAnswer provides a mock function with given fields: patientId
func (_m *QuestionaireData) CheckCountAttemptAnswer(patientId string) (int, error) {
	ret := _m.Called(patientId)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(patientId)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(patientId)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(patientId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAllQuestion provides a mock function with given fields:
func (_m *QuestionaireData) CountAllQuestion() (int, error) {
	ret := _m.Called()

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAttemptByMonth provides a mock function with given fields: month
func (_m *QuestionaireData) CountAttemptByMonth(month int) (int, error) {
	ret := _m.Called(month)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (int, error)); ok {
		return rf(month)
	}
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(month)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAttemptByStatusAssessment provides a mock function with given fields: status
func (_m *QuestionaireData) CountAttemptByStatusAssessment(status string) (int, error) {
	ret := _m.Called(status)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(status)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(status)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountQuestionerAttempt provides a mock function with given fields:
func (_m *QuestionaireData) CountQuestionerAttempt() (int, error) {
	ret := _m.Called()

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func() (int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountTestAttempt provides a mock function with given fields: patientId
func (_m *QuestionaireData) CountTestAttempt(patientId string) (questionaire.CoreAttempt, int, error) {
	ret := _m.Called(patientId)

	var r0 questionaire.CoreAttempt
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (questionaire.CoreAttempt, int, error)); ok {
		return rf(patientId)
	}
	if rf, ok := ret.Get(0).(func(string) questionaire.CoreAttempt); ok {
		r0 = rf(patientId)
	} else {
		r0 = ret.Get(0).(questionaire.CoreAttempt)
	}

	if rf, ok := ret.Get(1).(func(string) int); ok {
		r1 = rf(patientId)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(patientId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// InsertAnswer provides a mock function with given fields: idAttempt, data
func (_m *QuestionaireData) InsertAnswer(idAttempt string, data []questionaire.CoreAnswer) error {
	ret := _m.Called(idAttempt, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []questionaire.CoreAnswer) error); ok {
		r0 = rf(idAttempt, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertTestAttempt provides a mock function with given fields: data
func (_m *QuestionaireData) InsertTestAttempt(data questionaire.CoreAttempt) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(questionaire.CoreAttempt) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectAll provides a mock function with given fields:
func (_m *QuestionaireData) SelectAll() ([]questionaire.Core, error) {
	ret := _m.Called()

	var r0 []questionaire.Core
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]questionaire.Core, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []questionaire.Core); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]questionaire.Core)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewQuestionaireData interface {
	mock.TestingT
	Cleanup(func())
}

// NewQuestionaireData creates a new instance of QuestionaireData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQuestionaireData(t mockConstructorTestingTNewQuestionaireData) *QuestionaireData {
	mock := &QuestionaireData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
